### ISSUE TITLE
help using this function 

### ISSUE THREAD

**Issue by AciesGecko** [mamoruuu/random-reddit#13]
Hello, I'm so sorry I have no idea what I am doing, I just want to type .cat and make a bot post a random image from a subreddit with cats, I tried a lot of things but nothing works and I can't find a guide on how to use functions, it always give me errors, here's what I wrote:

```
client.on('messageCreate', message => {
    if (message.content.toLowerCase().startsWith('.cat')) {
        if (message.author.bot) return;
		message.delete();
		async function getImage(cats) {
		const picture = await getImage('cats')
		console.log(picture)
		message.channel.send("here cat")
		message.channel.send(picture)
		}
	}
});
```

Can you help me please, I don't even know where to search for help

**Comment by AlexAtHome** [comment]
In the snippet you provided you're declaring a new function without actually calling it. Like this
```js
await getImage(something here)
```
But I think you don't need to declare it. You only need to get the image and send it.

```js
message.delete();
const picture = await getImage('cats')
message.channel.send("here cat")
message.channel.send(picture)
```
Also, `getImage` - is an asynchronous function (it returns a `Promise`), so you have to put `async` in the first line

```js
client.on('messageCreate', async message => {
```
You can read more about Promises here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises

**Comment by AciesGecko** [comment]
Thank you so much for the quick reply, all is working fine now!
