### ISSUE TITLE
No Error Handling

### ISSUE THREAD

**Issue by SwiftSki** [mamoruuu/random-reddit#2]
I have an app that grabs a post from a subreddit specifies by the user. Whenever the user enters a subreddit that doesn't exist, the console gets spammed with `Assertion failed: [random-reddit] Request retries limits exceeded!` . There is no way to detect or stop this

**Comment by AlexAtHome** [comment]
Hello, @SwiftSki 

>subreddit that doesn't exist

Didn't think about this case at all. Those retry limits are supposed to prevent you from being banned by Reddit API. I'll remake error handling in the next few days to handle errors.

>the console gets spammed

The lib isn't supposed to spam with requests or assertion errors. Can you, please, show me the code snippet of the post request?

**Comment by SwiftSki** [comment]
The code that make the request is
``let post = await reddit.getPost(msg2);``, where msg2 is the string with the subreddit name

Thank you so much

**Comment by AlexAtHome** [comment]
>The code that make the request is

I mean, it's not in a some kind of loop (`while`, `for`, etc), right?

**Comment by SwiftSki** [comment]
It's not in a loop

**Comment by AlexAtHome** [comment]
@SwiftSki I do can reproduce your issue easily. Working on it right now

**Comment by AlexAtHome** [comment]
@SwiftSki fixed it in 1.2.3, try it out

If you pass non-existent subreddit into `getPost` (or any other method), it should return `null`
