### ISSUE TITLE
403 token errors

### ISSUE THREAD

**Issue by sudocode1** [mamoruuu/random-reddit#3]
i keep gettiing `The token retrieved was undefined. The username which we couln't get a token for is: sudocode1uwubot` (please ignore the name lmao), am i meant to put MY (u/sudocode1) username and password or am i doing something wrong? 
![image](https://user-images.githubusercontent.com/52894745/114283209-78311880-9a40-11eb-9c43-3599624260c1.png)

code used to fetch
```js
await reddit.getImage(reddits[Math.floor(Math.random() * reddits.length)])
            .then(x => {
                message.channel.send(x); // (discord)
            });
```

**Comment by AlexAtHome** [comment]
@sudocode1, I'm soooo sorry for delay, I was extremely busy last week

This error might occur if you have 2FA enabled on your account. Try using another account.

I'll put a warning about it in the README file

**Comment by AlexAtHome** [comment]
Actually, I'm now making a 2.0.0 version. You probably want to wait for it as I will *completely remove the authentication*.

**Comment by sudocode1** [comment]
alright,ill wait in that case

**Comment by sudocode1** [comment]
thank u for the help :D

**Comment by AlexAtHome** [comment]
> alright,ill wait in that case

@sudocode1 it's done :)

https://github.com/mamoruuu/random-reddit/releases/tag/2.0.0
