### ISSUE TITLE
Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by GalardoDev** [mamoruuu/random-reddit#4]
Hi.

I'm getting this Error, i tried to find out what could be possible problem, but didn't found anyone.
I installed package with npm, but it didn't appear in node_modules, so i added i manually, but it still doesn't works.

**Comment by AlexAtHome** [comment]
Hi, @GalardoDev 

Apparently, I forgot to *build* the library before releasing it.
I'm really sorry for that, but thank you for opening this issue though.
I just released a new version 2.0.1 with actual library files in it. Try it out. I think that will do for now, but I'll make sure that won't happen again in the future.

**Comment by GalardoDev** [comment]
There is no more error(s).
Thanks!

**Comment by ulisesvina** [comment]
It seems this error is repeating on version 2.0.2. @alstrnc
