### ISSUE TITLE
random-reddit\dist folder is gone after installing or updating to version 2.0.2

### ISSUE THREAD

**Issue by markpaul099** [mamoruuu/random-reddit#9]

**Comment by markpaul099** [comment]
and package.json main still points to dist/index.js on 2.0.2

**Comment by AlexAtHome** [comment]
@markpaul099 
That's strange.
I'll fix it very soon. Try installing `random-reddit@2.0.2-2` for now

**Comment by AlexAtHome** [comment]
@markpaul099, I couldn't *republish* the 2.0.2 version so I published the 2.0.3 instead.
```sh
npm install random-reddit@latest
```
